Web_Track/kct_sms/sms/manager/urls.py
# from django.contrib import admin
from django.urls import path
from . import views

app_name = "manager"
urlpatterns = [
    path('', views.home, name="home"),
    path('register/', views.register, name="register"),
    path('login/', views.loginpage, name="loginpage"),
    path('logout/', views.logoutpage, name="logoutpage"),
    path('leave/', views.apply_leave, name="apply_leave"),
    path('view_leave/', views.view_leave, name="view_leave"),
]

Web_Track/kct_sms/sms/sms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("manager.urls")),
]

Web_Track/kct_sms/sms/manager/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Place(models.Model):
    place_name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.place_name


class SecurityRoutine(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(null = True)
    start_time = models.TimeField(null = True)
    end_time = models.TimeField(null = True)
    place = models.ForeignKey(Place, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name.username


class Leave(models.Model):
    from_date = models.DateField(null = True)
    to_date = models.DateField(null = True)
    name = models.ForeignKey(User, on_delete = models.CASCADE)
    reason = models.CharField(max_length=200, null=True, blank = True)

    def __str__(self):
        return self.name.username

Web_Track/kct_sms/sms/manager/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUser(UserCreationForm):
    # type = models.CharField(choices = ['security', 'manager'])
    idno = forms.IntegerField()
    class Meta:
        model = User
        fields = ('username', "idno", "password1", "password2")

class LeaveForm(forms.Form):
    class Meta:
        model = Leave
        fields = ["from_date", "to_date", "reason"]

Web_Track/kct_sms/sms/manager/views.py
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import *

from .forms import *

# Create your views here.

def register(request):
    if request.user.is_authenticated:
        return redirect(reverse('manager:home'))
    else:
        form = CreateUser()
        if request.method == 'POST':
            form = CreateUser(request.POST)
            if form.is_valid():
                form.save()
                username = request.POST.get('username')
                messages.success("Account is created for: ", username)
                return redirect(reverse('manager:loginpage'))

        return render(request, "manager/register.html", {
            "form": form,
        })

def loginpage(request):
    if request.user.is_authenticated:
        return redirect(reverse('manager:home'))
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            idno = request.POST.get('idno')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('manager:home'))

        return render(request, "manager/login.html", {

    })


def logoutpage(request):
    if request.method == "POST":
        logout(request)
        return redirect(reverse("manager:loginpage"))
    
    return redirect(reverse("manager:loginpage"))


@login_required(login_url="manager:loginpage")
def home(request):
    my_routine = SecurityRoutine.objects.filter(name = request.user)
    leave_applied = Leave.objects.filter(name=request.user)
    return render(request, 'manager/home.html', {
        "routines": my_routine,
        "leave_applied": leave_applied,
    })

def view_leave(request):
    leave_applied = Leave.objects.filter(name=request.user)
    return render(request, 'manager/leaves.html', {
        "leave_applied": leave_applied,
    })


def apply_leave(request):
    leave_form = LeaveForm()
    return render(request, "manager/apply_leave.html", {
        "form": leave_form,
    })

Web_Track/kct_sms/sms/manager/templates/manager/apply_leave.html
{% extends "manager/main.html"%}

{% block content %}

<form method="post" action="">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Apply">
</form>

{% endblock %}

Web_Track/kct_sms/sms/manager/templates/manager/home.html
{% extends "manager/main.html"%}

{% block content %}
<h1>Home page</h1>
<br>
{% for routine in routines %}
    <h3>Date: {{ routine.date }}</h3>
    <h3>Start time: {{ routine.start_time }}</h3>
    <h3>End Time: {{ routine.end_time }}</h3>
    <h3>Place: {{ routine.place }}</h3>
    <br>
{% endfor %}

{% endblock %}

Web_Track/kct_sms/sms/manager/templates/manager/leaves.html
{% extends "manager/main.html"%}

{% block content %}
<h1>Leave management</h1>
<br>
{% for leave in leave_applied %}
    <h3>Date: {{ leave.from_date }}</h3>
    <h3>Start time: {{ leave.to_date }}</h3>
    <h3>End Time: {{ leave.reason }}</h3>
    <br>
{% endfor %}

{% endblock %}

Web_Track/kct_sms/sms/manager/templates/manager/login.html
{% extends "manager/main.html"%}


{% block content %}
<h1>Login Page</h1>

<form method="post" action="">
    {% csrf_token %}
    <input type="text", name="username", placeholder="Username">
    <input type="text", name="idno", placeholder="ID_No">
    <input type="text", name="password", placeholder="Password">
    <input type="submit" value="Signup">
</form>
{% for message in messages %}
    {{ message }}
{% endfor %}

{% endblock %}

Web_Track/kct_sms/sms/manager/templates/manager/main.html
<DOCTYPE html>
<html>
    <head>
        <title>Security Management System</title>
    </head>
    <body>
        {% if user.is_authenticated %}
        <h2>Navbar {{ user }}</h2>
        <form method="post" action="{% url 'manager:logoutpage'%}">
            {% csrf_token %}
            <input type="submit" name="logout" value="Logout">
        </form>
        {% else %}
        <a href="{% url 'manager:loginpage'%}">Login</a>
        <a href="{% url 'manager:register'%}">Signup</a>
        {% endif %}
        <a href="{% url 'manager:home' %}">Dashboard</a>
        <a href="{% url 'manager:apply_leave' %}">Apply Leave</a>
        <a href="{% url 'manager:view_leave' %}">View Leave</a>
        <hr>
        {% block content %}

        {% endblock %}
        <hr>
        <h2>Footer</h2>
    </body>
</html>

Web_Track/kct_sms/sms/manager/templates/manager/register.html
{% extends "manager/main.html"%}


{% block content %}
<h1>Register page</h1>

<form method="post" action="">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup"></input>
</form>

{% endblock %}