Web_Track/Brain/test_project/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("deva", views.deva, name="deva"),
    path("kum", views.kum, name="kum")
]

Web_Track/Brain/test_project/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

Web_Track/Brain/test_project/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path("clear", views.clear, name="clear")
]

Web_Track/Brain/test_project/test_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
]

Web_Track/Brain/test_project/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request) :
    return render(request, "hello/index.html")

def deva(request) :
    return HttpResponse("Hello, devasenan!")

def kum(request) :
    return HttpResponse("Hello, kumaresan!")

def greet(request, name) :
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

Web_Track/Brain/test_project/newyear/views.py
from django.shortcuts import render
from datetime import datetime as dt
# Create your views here.

#we can also do the same thing as,
'''
now = dt.now()
if now.month == 1 and now.day == 1 :
    newyear = Yes
else :
    newyear = No
return render(request, "newyear/index.html", {
    "newyear : newyear
    })
'''

def index(request) :
    now = dt.now()
    return render(request, "newyear/index.html", {
        "newyear" : now.month == 1 and now.day == 1 
    }) 

Web_Track/Brain/test_project/tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# Create your views here.

class NewTaskForm(forms.Form) :
    task = forms.CharField(label="New Task")
    #priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

def index(request):
    if "tasks" not in request.session :
        request.session["tasks"] = []   # creating a empty list for each users or sessions  
        ''' sessions store data about our each visits, it stores info like ID or info about you in this case our tasks.
        sessions are like big dictionary.'''
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"] # this passes that list, i created above.
    })

def add(request) :
    if request.method == "POST" :
        form = NewTaskForm(request.POST)
        if form.is_valid() :       # server side validation.
            task = form.cleaned_data["task"]
            if task not in request.session["tasks"] :
                request.session["tasks"] += [task]
                return HttpResponseRedirect(reverse("tasks:index"))
            return render(request, 'tasks/add.html', {
                "form" : form,
                "added" : "Task already added!!"
            })
        else :
            return render(request, "tasks/add.html", {
                "form" : form
            })
    return render(request, "tasks/add.html", {
        "form" : NewTaskForm()
    })


def clear(request) :
    if "tasks" in request.session :
        request.session.pop("tasks") # used a dict method to del the item "tasks" in the dict session.
    request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks" : request.session["tasks"]   
    })

Web_Track/Brain/test_project/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}

<h1>Add tasks</h1>
<form action="{% url 'tasks:add' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
<h5>{{added}}</h5>
<a href="{% url 'tasks:index'%}">View tasks</a>

{% endblock %}

Web_Track/Brain/test_project/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<div class="container">
<h1>Tasks</h1>
<ul>
    {% for task in tasks %}
        <li>{{ task }}</li>
    {% empty %}
        <li>No tasks.</li>
    {% endfor %}
</ul>
<a href="{% url 'tasks:add'%}">Add tasks</a>
<a href="{% url 'tasks:clear' %}">Clear Tasks</a>
</div>
{% endblock %}

Web_Track/Brain/test_project/tasks/templates/tasks/layout.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Tasks</title>
</head>

<body>

    {% block body %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>